### ISSUE TITLE
Healthpacks

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#54]
We want to introduce Healthpacks, so player can add health +500, if he find (and collides) with such an health pack.

Drop this packs is issue #58 .

**Comment by JuKu** [comment]
Maybe we should create this entity in an ItemFactory.

**Comment by crykn** [comment]
The entity creation is already implemented in a PowerupFactory .

**Comment by JuKu** [comment]
@crykn nice! :D 
So this issue is resolved?

**Comment by crykn** [comment]
Nope, the assets and the actual spawning of the powerups are still missing. But for that see #58

**Comment by JuKu** [comment]
@crykn Thanks! :D
